services:
  users-db:
    image: mongo:7
    volumes:
      - users-db-data:/data/db
    networks:
      - users-net

  products-db:
    image: mongo:7
    volumes:
      - products-db-data:/data/db
    networks:
      - products-net

  users-service:
    build: ./services/users-service
    environment:
      MONGO_URI: mongodb://users-db:27017
    depends_on:
      - users-db
    networks:
      - users-net
      - edge-net

  products-service:
    build: ./services/products-service
    environment:
      MONGO_URI: mongodb://products-db:27017
    depends_on:
      - products-db
    networks:
      - products-net
      - edge-net

  lb:
    image: nginx:alpine
    volumes:
      - ./lb/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - users-service
      - products-service
    networks:
      - edge-net
      - public-net

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - lb
    networks:
      - public-net

networks:
  users-net:
    driver: bridge
    internal: true
  products-net:
    driver: bridge
    internal: true
  edge-net:
    driver: bridge
    internal: true
  public-net:
    driver: bridge

volumes:
  users-db-data:
  products-db-data:
